default_stages: [commit]
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v1.17.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: clean and build
        name: clean and build
        entry: bash -c "./gradlew clean build -x test -x spotlessCheck"
        language: system
        require_serial: true
      - id: code formatter
        name: code formatter
        entry: bash -c "./gradlew spotlessCheck"
        language: system
        require_serial: true
